/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      screens: {
        xs: "400px",
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
      },
      colors: {
        background: "rgb(var(--tw-background) / <alpha-value>)",
        foreground: "rgb(var(--tw-foreground) / <alpha-value>)",
        card: "rgb(var(--tw-card) / <alpha-value>)",
        muted: "rgb(var(--tw-muted) / <alpha-value>)",
        "muted-foreground": "rgb(var(--tw-muted-foreground) / <alpha-value>)",
        primary: "rgb(var(--tw-primary) / <alpha-value>)",
        "primary-foreground": "#ffffff",
        secondary: "rgb(var(--tw-secondary) / <alpha-value>)",
        "secondary-foreground": "rgb(var(--tw-secondary-foreground) / <alpha-value>)",
        destructive: "rgb(var(--tw-destructive) / <alpha-value>)",
        danger: "rgb(var(--tw-danger) / <alpha-value>)",
        border: "rgb(var(--tw-border) / <alpha-value>)",
        accent: "rgb(var(--tw-accent) / <alpha-value>)",
        ring: "rgb(var(--tw-primary) / <alpha-value>)",
        saffron: "rgb(var(--tw-primary) / <alpha-value>)",
        vermilion: "rgb(var(--tw-destructive) / <alpha-value>)",
        gold: "#d4a017",
        "surface-inset": "rgb(var(--tw-surface-inset) / <alpha-value>)",
        "surface-muted": "rgb(var(--tw-surface-muted) / <alpha-value>)",
        "surface-today": "rgba(198, 40, 40, 0.14)",
        "surface-today-hover": "rgba(198, 40, 40, 0.22)",
        "surface-hover": "rgba(217, 119, 6, 0.07)",
        "surface-tint-danger": "rgba(198, 40, 40, 0.07)",
        "tab-active": "rgba(var(--tw-tab-active) / 0.12)",
        "tab-hover": "rgba(var(--tw-tab-active) / 0.06)",
        "fest-today": "rgba(198, 40, 40, 0.08)",
      },
      fontFamily: {
        sans: ["Mukta_400Regular"],
        medium: ["Mukta_500Medium"],
        semibold: ["Mukta_600SemiBold"],
        bold: ["Mukta_700Bold"],
        mono: ["FiraCode_400Regular"],
        num: ["FiraCode_400Regular"],
        "num-bold": ["FiraCode_700Bold"],
      },
      borderRadius: {
        lg: "8px",
        xl: "12px",
      },
    },
  },
  plugins: [],
};
